<?xml version="1.0" encoding="utf-8"?><Database Name="EmptyProject" Class="EmptyProjectDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=EmptyProject;Persist Security Info=True;User ID=sa" SettingsObjectName="EmptyProject.Models.Properties.Settings" SettingsPropertyName="EmptyProjectConnectionString3" Provider="System.Data.SqlClient" />
</Database>